### ISSUE TITLE
 Suggestions for additional templates of Pull requests

### ISSUE THREAD

**Issue by kip2** [Team-GREEN-Recursion/git-workshop#11]
**対処概要**

プルリク時のテンプレートに「次回担当したい作業」を追加する

**対処内容**

プルリク時のテンプレートに「次回担当したい作業」の追加を提案します。
プルリク時に次回担当したい作業がわかるので、確認の手間が減ることで作業が効率化できそうです。

例外として、希望がかぶった場合について。
この場合は、その都度話し合いの場を設けて決めるとよいのではと思います。

**関連チケット**

～ 関連する issue / pull request を明記する ～

**関連資料**

～ 設計書のパス(URL）を明記する

**チェックリスト**

**特記事項**

**Comment by yuki-akiba-jp** [comment]
issueの作成ありがとうございます！
テンプレートに追加しときました。
